# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('ordinal', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
