# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igenapp', '0002_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('R', 'RED'), ('B', 'BLUE'), ('Y', 'YELLOW'), ('G', 'GREEN')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('creation_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='issue',
            name='label',
            field=models.ManyToManyField(to='igenapp.Label'),
        ),
        migrations.AddField(
            model_name='issue',
            name='milestone',
            field=models.ManyToManyField(to='igenapp.Milestone'),
        ),
    ]
