# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igenapp', '0003_auto_20180117_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=40),
        ),
    ]
