# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igenapp', '0003_auto_20180116_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(choices=[('#ee0701', 'RED'), ('B', 'BLUE'), ('Y', 'YELLOW'), ('G', 'GREEN')], max_length=1),
        ),
    ]
