# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igenapp', '0004_auto_20180117_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='milestone',
        ),
        migrations.AddField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='igenapp.Milestone'),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(choices=[('R', '#ee0701'), ('B', '#84b6eb'), ('Y', '#fbca04'), ('G', '#33aa3f')], max_length=1),
        ),
    ]
