# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igenapp', '0006_auto_20180117_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
