# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igenapp', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
