# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 00:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('igenapp', '0010_auto_20180121_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=70)),
                ('owner_name', models.CharField(max_length=70)),
                ('type', models.CharField(choices=[('L', 'Local'), ('G', 'Git')], default='L', max_length=1)),
                ('url', models.CharField(default='', max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contributors', models.ManyToManyField(related_name='contributors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
